export const SET_COMPLETE_ACTION = 'SET_COMPLETE_ACTION';
export const TOGGLE_COMPLETE_ACTION = 'TOGGLE_COMPLETE_ACTION';
export const SET_ACTIVE_ACTION = 'SET_ACTIVE_ACTION';
export const EDIT_ACTION = 'EDIT_ACTION';
export const DELETE_ACTION = 'DELETE_ACTION';

export const EDITING_ACTION_CHANGE = 'EDITING_ACTION_CHANGE';
export const EDITING_ACTION_COMMIT = 'EDITING_ACTION_COMMIT';
export const EDITING_ACTION_BLUR = 'EDITING_ACTION_BLUR';
export const EDITING_ACTION_CANCEL = 'EDITING_ACTION_CANCEL';
